
// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `EntityGeneration`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=(LocalDb)\MSSQLLocalDB;AttachDbFilename=D:\Projects\Dapper.FastCRUD\Dapper.FastCRUD.Tests\App_Data\\TestDatabase.mdf;Initial Catalog=TestDatabase;Integrated Security=True`
//     Include Views:          `True`

namespace Dapper.FastCrud.Tests.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the SingleIntPrimaryKeyEntities table.
    /// </summary>
	[Table("SingleIntPrimaryKeyEntities")]
	public partial class SingleIntPrimaryKeyEntity
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string FirstName { get; set; }
		public virtual string LastName { get; set; }
		public virtual DateTime? DateOfBirth { get; set; }
	}

}

